In [2]:
pip install numpy

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import numpy as np

In [5]:
myarr = np.array([3,10,54,7,2,32,16,8])

In [6]:
myarr

array([ 3, 10, 54,  7,  2, 32, 16,  8])

In [7]:
myarr = np.array([3,10,54,7,2,32,16,8], np.int8)

In [8]:
myarr

array([ 3, 10, 54,  7,  2, 32, 16,  8], dtype=int8)

In [9]:
myarr[3]

7

In [10]:
myarr[7]

8

In [11]:
arr = np.array([[3,6,37,7]], np.int64)

In [12]:
arr

array([[ 3,  6, 37,  7]])

In [13]:
arr[0]

array([ 3,  6, 37,  7])

In [14]:
arr[0,2]

37

In [15]:
arr[0,1]

6

In [16]:
myarr.shape

(8,)

In [17]:
arr.shape

(1, 4)

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr[0,1] = 45

In [20]:
arr

array([[ 3, 45, 37,  7]])

In [21]:
#Array creation : Conversion from other python structures#
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])


In [22]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [23]:
listarray.dtype

dtype('int64')

In [24]:
zeroes = np.zeros((2,5))

In [25]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace = np.linspace(1,50,10)

In [29]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [38]:
emp = np.empty(2)

In [39]:
emp

array([4.6856516e-310, 4.9406565e-324])

In [46]:
emp_like = np.empty_like(lspace)

In [47]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [48]:
emp_like.dtype

dtype('float64')

In [49]:
ey = np.eye(2,3,1)

In [50]:
ey

array([[0., 1., 0.],
       [0., 0., 1.]])

In [54]:
ey = np.eye(3,3,-1)

In [55]:
ey

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [56]:
id = np.identity(4)

In [57]:
id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
ar = np.arange(64)

In [59]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [61]:
ar = ar.reshape(8,8)

In [62]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [63]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [64]:
ar = ar.ravel()

In [65]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [66]:
ar.shape

(64,)

In [67]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [68]:
aar = np.array(x)

In [69]:
aar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
aar.sum(axis=0)

array([12,  8,  9])

In [71]:
aar.sum(axis=1)

array([ 6, 15,  8])

In [72]:
aar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [73]:
aar.flat

In [74]:
for item in aar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [75]:
aar.ndim

2

In [76]:
ar.ndim

1

In [77]:
aar.size

9

In [78]:
ar.size

64

In [80]:
aar.shape

(3, 3)

In [82]:
ar.shape

(64,)

In [83]:
aar.nbytes

72

In [84]:
one = np.array([1,3,4,634,2])

In [85]:
one

array([  1,   3,   4, 634,   2])

In [86]:
one.argmax()

3

In [88]:
one.argmin()

0

In [89]:
one.argsort()

array([0, 4, 1, 2, 3])

In [103]:
aar


array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [104]:
aar.min()

0

In [105]:
aar.max()

7

In [106]:
aar.argmin()

6

In [107]:
aar.argmax()

8

In [108]:
aar.argmax(axis=0)

array([1, 1, 2])

In [109]:
aar.argmin(axis=0)

array([2, 2, 0])

In [110]:
aar.argmax(axis=1)

array([2, 2, 2])

In [111]:
aar.argmin(axis=1)

array([0, 0, 0])

In [112]:
aar


array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [113]:
aar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [115]:
aar.argsort(axis=0)

array([[2, 2, 0],
       [0, 0, 1],
       [1, 1, 2]])

In [117]:
a1 = np.array([[2,3,1],
               [1,2,3],
               [4,5,6]])

In [118]:
a1

array([[2, 3, 1],
       [1, 2, 3],
       [4, 5, 6]])

In [119]:
y = ([6,7,4],[3,2,1],[1,4,2])

In [120]:
a2 = np.array(y)

In [121]:
a2

array([[6, 7, 4],
       [3, 2, 1],
       [1, 4, 2]])

In [122]:
a1 + a2

array([[ 8, 10,  5],
       [ 4,  4,  4],
       [ 5,  9,  8]])

In [128]:
a3 = a2-a1

In [129]:
a3

array([[ 4,  4,  3],
       [ 2,  0, -2],
       [-3, -1, -4]])

In [131]:
a3.sum()

3

In [124]:
a1*a2

array([[12, 21,  4],
       [ 3,  4,  3],
       [ 4, 20, 12]])

In [125]:
a1/a2

array([[0.33333333, 0.42857143, 0.25      ],
       [0.33333333, 1.        , 3.        ],
       [4.        , 1.25      , 3.        ]])

In [127]:
np.sqrt(a1)

array([[1.41421356, 1.73205081, 1.        ],
       [1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [132]:
a2.sum()

30

In [133]:
np.where(a2>5)

(array([0, 0]), array([0, 1]))

In [135]:
np.where(a1<0)

(array([], dtype=int64), array([], dtype=int64))

In [136]:
np.count_nonzero(a1)

9

In [137]:
np.nonzero(a2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [138]:
a2[1,2] = 0

In [139]:
np.nonzero(a2)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))